datasources:
  default:
    db-type: postgres
micronaut:
  application:
    name: mnwebsample
datasources:
  default:
    url: ${MWWEB_DB_URL:`jdbc:postgresql://localhost:5432/default_database`}
    username: ${MWWEB_DB_USER:`default_username`}
    password: ${MWWEB_DB_PASSWORD:`default_password`}
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES